version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  reviewers:
  - tomas-stefano
  - brenetic
  - mattempty
  - njseeto
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  reviewers:
  - mattempty
  - form-builder-developers
  - tomas-stefano
  - brenetic
  - njseeto
- package-ecosystem: docker
  directory: "/docker/web"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  reviewers:
  - tomas-stefano
  - brenetic
  - mattempty
  - njseeto
- package-ecosystem: docker
  directory: "/docker/workers"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  reviewers:
  - tomas-stefano
  - brenetic
  - mattempty
  - njseeto
- package-ecosystem: docker
  directory: "/acceptance"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  reviewers:
  - tomas-stefano
  - brenetic
  - mattempty
  - njseeto
