version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  reviewers:
  - tomas-stefano
  - brenetic
  - mattempty
  - njseeto
  ignore:
  - dependency-name: webpacker
    versions:
    - 5.2.2
  - dependency-name: metadata_presenter
    versions:
    - 0.10.0
    - 0.11.0
    - 0.12.0
    - 0.13.1
    - 0.13.2
    - 0.13.3
    - 0.13.4
    - 0.14.1
    - 0.15.0
    - 0.15.1
    - 0.15.2
    - 0.17.1
    - 0.18.0
    - 0.19.0
    - 0.19.1
    - 0.19.2
    - 0.20.0
    - 0.21.0
    - 0.27.1
    - 0.27.3
    - 0.28.12
    - 0.28.6
    - 0.28.7
    - 0.28.8
    - 0.3.2
    - 0.4.0
    - 0.5.0
    - 0.6.0
    - 0.7.0
    - 0.8.0
    - 0.8.1
    - 0.8.2
    - 0.9.0
    - 1.0.2
  - dependency-name: faraday
    versions:
    - 1.3.1
  - dependency-name: sentry-ruby
    versions:
    - 4.3.2
  - dependency-name: sentry-rails
    versions:
    - 4.3.3
  - dependency-name: rspec-rails
    versions:
    - 4.1.0
    - 4.1.1
    - 5.0.0
  - dependency-name: rails
    versions:
    - 6.1.2
  - dependency-name: capybara
    versions:
    - 3.35.2
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  reviewers:
  - mattempty
  - form-builder-developers
  - tomas-stefano
  - brenetic
  - njseeto
  ignore:
  - dependency-name: marked
    versions:
    - 2.0.2
- package-ecosystem: docker
  directory: "/docker/web"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  reviewers:
  - tomas-stefano
  - brenetic
  - mattempty
  - njseeto
  ignore:
  - dependency-name: ruby
    versions:
    - 3.0.0.pre.alpine3.12
    - 3.0.1.pre.alpine3.12
- package-ecosystem: docker
  directory: "/docker/workers"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  reviewers:
  - tomas-stefano
  - brenetic
  - mattempty
  - njseeto
  ignore:
  - dependency-name: ruby
    versions:
    - 3.0.0.pre.alpine3.12
    - 3.0.1.pre.alpine3.12
- package-ecosystem: docker
  directory: "/acceptance"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  reviewers:
  - tomas-stefano
  - brenetic
  - mattempty
  - njseeto
  ignore:
  - dependency-name: ruby
    versions:
    - 3.0.0.pre.alpine
    - 3.0.1.pre.alpine
