apiVersion: v1
kind: ConfigMap
metadata:
  name: fb-editor-config-map
  namespace: formbuilder-saas-{{ .Values.environmentName }}
data:
  RAILS_ENV: production
  RAILS_LOG_TO_STDOUT: "true"
  PLATFORM_ENV: {{ .Values.environmentName }}
  RAILS_SERVE_STATIC_FILES: "true"
