apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: "fb-editor-ing-{{ .Values.environmentName }}"
spec:
  tls:
  - hosts:
    - {{ .Values.editor_host }}
    secretName: editor-tls-certificate
  rules:
  - host: {{ .Values.editor_host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: fb-editor-svc-{{ .Values.environmentName }}
          servicePort: 80
