apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: "fb-editor-ing-{{ .Values.environmentName }}"
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
spec:
  tls:
  - hosts:
    - {{ .Values.editor_host }}
  rules:
  - host: {{ .Values.editor_host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: fb-editor-svc-{{ .Values.environmentName }}
          servicePort: 80
