apiVersion: v1
kind: Secret
metadata:
  name: fb-editor-secrets-{{ .Values.environmentName }}
  namespace: formbuilder-saas-{{ .Values.environmentName }}
type: Opaque
data:
  secret_key_base: {{ .Values.secret_key_base }}
  auth0_client_id: {{ .Values.auth0_client_id }}
  auth0_client_secret: {{ .Values.auth0_client_secret }}
  encoded_private_key: {{ .Values.encoded_private_key}}
